### PR TITLE
API-Key

### PR DESCRIPTION
**Pull request by marlbones**
Hey, I just created this example config file in a data folder. If you'd prefer a different way to store key and url info or if you'd like a different naming convention all good!

### CODE REVIEW

**Comment by robhung** [comment]
Actually, that's a good idea - for some reason, I was thinking to just have one key to use but it's probably better for us to use our own API key.

In saying that, I would suggest adopting environment variables instead of `config.js` and then adding in the README some instructions on how to get the API key and to copy the `example.env` to `.env` and replace the placeholder with your own key.

**Comment by marlbones** [comment]
Sweet, adjusted it. Added a .env example file and added this package (https://github.com/zetachang/react-native-dotenv) to access .env files. You'll see that installation docs say to add a line to a .babelrc file, however I added this to our babel.config.js file and it seemed to work fine. I also works fine without it, so maybe we just have to keep an eye on it.

**Comment by robhung** [comment]
> Sweet, adjusted it. Added a .env example file and added this package (https://github.com/zetachang/react-native-dotenv) to access .env files. You'll see that installation docs say to add a line to a .babelrc file, however I added this to our babel.config.js file and it seemed to work fine. I also works fine without it, so maybe we just have to keep an eye on it. Alternatively we just remove the line for now.

I think it may have to do with when it gets deployed as `babel` is usually used when transpiling code, so we won't be able to test this until we deploy the app. In the meantime, I've removed it since we can't actually test it.

**Comment by robhung** [comment]
Also noticed the docs said to install it as a devDependency, so I've made that change for you in a new commit!

**Pull request merged**
